name: Develop

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run sbt clean compile
        run: |
          sbt clean compile
  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run sbt stage deployHeroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }},
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }},
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }},
          MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }},
          LOG_LEVEL: DEBUG,
          MONGO_DATABASE: dev_kezek,
          MONGO_PRODUCT_COLLECTION: product,
          MONGO_CATEGORY_COLLECTION: category,
          HOST: 0.0.0.0,
          SWAGGER_SCHEMES: https,
          ENV: dev,
        run: |
          sbt -Denv=dev stage deployHeroku